$(function () {
	var window_height = document.all ? document.getElementsByTagName("html")[0].offsetHeight : window.innerHeight ;
	var width = $("#partA").width();
	$("#set_font_size").css("font-size",width/25);
	var heightA = window_height * 0.25; 
	$("#partA").css('height', heightA);			
	var heightB = window_height * 0.4; 
	$("#partB").css('height', heightB);
	$("#partC").css('top', heightA);
	var heightC = window_height * 0.6; 
    $("#partC").css('height', heightC);
	$("#partD").css('top', heightA + heightC);
    var height = $("#temprature_div").width()/3; 
    $("#temprature_div").css('height', height);
	height = $("#PM_evaluation").width()/2;
	$("#PM_evaluation").css('height', height);
	$("#PM_evaluation").css('border-radius', height/2);
	height = $("#temprature_evaluation").width()/2;
	$("#temprature_evaluation").css('height', height);
	$("#temprature_evaluation").css('border-radius', height/2);
	height = $("#humidity_evaluation").width()/2;
	$("#humidity_evaluation").css('height', height);
	$("#humidity_evaluation").css('border-radius', height/2);
	height = $("#partC").width()/5; 
	$("#PM_div").css('height', height);
	$("#partB").css('top',height);
	height = $("#humidity_div").width()/3; 
	$("#humidity_div").css('height', height); 		
	var heightD = $("#partC").width()/8; 
	$("#partD").css('height', heightD);	
	draw_partA();
	draw_partB();
	draw_partC();
});